Make kubernetes and application-engine type current contexts mutual exclusive
vmware-tanzu/tanzu-plugin-runtime pull request #113
Opened 2023-10-04 19:39 UTC by prkalle

### What this PR does / why we need it
This PR makes kubernetes and application-engine current contexts mutual exclusive, which means if the k8s context is set as current(active) the TAE context would be removed and vice-versa.

### Which issue(s) this PR fixes

Fixes #

### Describe testing done for PR
Unit tests and CI passed.

### Release note

```release-note
Make kubernetes and application-engine type current contexts mutual exclusive
```

### Additional information

#### Special notes for your reviewer

2023-10-05 21:58 UTC, prkalle commented
> We need to add Compatibility tests for this change as well.

I will add the Compatibility tests in a follow up PR.

2023-10-09 14:39 UTC, marckhouzam approved these changes
Thanks @prkalle !
Two nits, but LGTM

2023-10-09 14:39 UTC, marckhouzam commented on config/contexts_test.go
> +		It("should set tmc context as current context successfully", func() {
title is wrong

2023-10-09 16:43 UTC, prkalle commented on config/contexts_test.go
> +	"github.com/onsi/gomega"
It was not imported into the current package on purpose as the gomega has global variable `Default` which was conflicting with `Default` global variable declared in `config` package.

2023-10-09 16:43 UTC, vuil commented on config/contexts.go
> +func updateMutualExclusiveCurrentContexts(node *yaml.Node, ctx *configtypes.Context) error {
nit: (I don't feel super strongly about this) I am wondering if we can write this in a more future proof manner by checking for TargetTMC instead.
iow, 
when ctx is not tmc:
   deactivate any ctx that is not tmc

then the code works even when new context types are introduced

2023-10-09 16:43 UTC, vuil commented on config/contexts_test.go
> +	"github.com/onsi/gomega"
+1

2023-10-09 16:43 UTC, vuil commented on config/contexts_test.go
> +		It("should have only k8s as current context and tae context should be removed from the curren context", func() {
typo curren, same for next It as well.

2023-10-09 16:44 UTC, prkalle commented on config/contexts_test.go
> +		It("should set tmc context as current context successfully", func() {
Thanks, fixed.

2023-10-09 16:46 UTC, prkalle commented on config/contexts_test.go
> +		It("should have only k8s as current context and tae context should be removed from the curren context", func() {
fixed.

2023-10-09 16:50 UTC, marckhouzam reviewed
@prkalle There is another `SetCurrentContext()` function in `clientconfig.go`.  It is not clear to me when that one is used, but I get the feeling it can and therefore it may need to be updated as well?

2023-10-09 16:51 UTC, marckhouzam requested changes
Blocking the PR until we discuss the last comment https://github.com/vmware-tanzu/tanzu-plugin-runtime/pull/113#pullrequestreview-1664937527

I was just afraid the comment would be missed since I added it after approving

2023-10-09 21:25 UTC, prkalle commented on config/contexts.go
> +func updateMutualExclusiveCurrentContexts(node *yaml.Node, ctx *configtypes.Context) error {
Sure. Updated the PR to maintain mutual exclusion behavior among all the current context types except TMC. Thanks

2023-10-09 21:29 UTC, prkalle commented
> @prkalle There is another `SetCurrentContext()` function in `clientconfig.go`. It is not clear to me when that one is used, but I get the feeling it can and therefore it may need to be updated as well?

`SetCurrentContext()` function in `clientconfig.go` is just to modify the current contexts in the client and user has to call `StoreClientConfig()` method inorder to persist the changes to the config file, which would internally call  `clientConfigSetCurrentContext()` that would endup calling the `setCurrentContext()` in context.go file. So we should be good without updating the `SetCurrentContext()` function in `clientconfig.go`.

cc: @mpanchajanya Thanks for clarification

2023-10-10 01:25 UTC, marckhouzam commented
Thanks for the explanation @prkalle (and @mpanchajanya ).  It makes sense.

2023-10-10 01:26 UTC, marckhouzam approved these changes
LGTM
Thanks @prkalle !

2023-10-10 05:09 UTC, merged