Compatibility tests to validate k8s and tanzu active context mutual exclusion behavior
vmware-tanzu/tanzu-plugin-runtime pull request #135
Opened 2023-11-07 19:11 UTC by prkalle

### What this PR does / why we need it
This PR addes compatibility tests to validate k8s and tanzu active context mutual exclusion behavior
### Which issue(s) this PR fixes

Fixes #

### Describe testing done for PR
CI tests passed

### Release note

```release-note

```

### Additional information

#### Special notes for your reviewer

2023-11-07 20:07 UTC, mpanchajanya commented on test/compatibility/framework/context/context_options.go
> +		c.Target = ""
Use WithTarget to set Target

2023-11-07 20:21 UTC, mpanchajanya requested changes
looks good. one minor nit

2023-11-08 17:53 UTC, prkalle commented on test/compatibility/framework/context/context_options.go
> +		c.Target = ""
I thought of it(using the WithTarget in tests) but I felt like with the latest ContextType, the target would not have relevance(user would leave it to  empty string) in the context tests hence I set Target to empty string whenever user chooses `WithContextType()`. I can change this if you think it would if user explicitly sets them to empty string using `WithTarget`. Let me know your thoughts.

2023-11-08 18:19 UTC, mpanchajanya commented on test/compatibility/framework/context/context_options.go
> +		c.Target = ""
makes sense now.  Thanks

2023-11-08 18:19 UTC, mpanchajanya approved these changes

2023-11-08 18:55 UTC, merged