Implement `logger`
vmware-tanzu/tanzu-plugin-runtime pull request #24
Opened 2023-03-01 23:05 UTC by anujc25

### What this PR does / why we need it

- Implement support for `logger` 
- This logger can be consumed by plugins to have consistent logging experience across tanzu-cli and plugins
- This has support for level-based logging
- It doesn't support colored logging at the moment

### Which issue(s) this PR fixes

Fixes #

### Describe testing done for PR

### Release note

```release-note
Add support for logger which can be consumed by the plugins for the logging to have a consistent logging experience
```

### Additional information

#### Special notes for your reviewer

2023-03-02 16:00 UTC, marckhouzam reviewed
One comment about `Errorf` inline.

Out of curiosity, why did you remove `SetChannel()` and `SendProgressUpdate()` which were in the logger in TF?

2023-03-02 17:40 UTC, chandrareddyp approved these changes
LGTM

2023-03-02 18:23 UTC, anujc25 commented
> Out of curiosity, why did you remove SetChannel() and SendProgressUpdate() which were in the logger in TF?

That section was more for specific use-case of sending logs to the kickstart UI. So, I felt it doesn't make sense to add it to this generic logger.

2023-03-02 21:52 UTC, anujc25 commented on log/log.go
> +func Errorf(format string, args ...interface{}) {
Thanks. Updated.

2023-03-03 02:42 UTC, marckhouzam requested changes
One suggested fix and one thing to possibly discuss

2023-03-03 02:42 UTC, marckhouzam commented on log/writer.go
> +	// If log type if OUTPUT skip the header
```suggestion
	// If log type is OUTPUT skip the header
```

2023-03-03 02:59 UTC, marckhouzam commented on log/writer.go
> +// NewWriter returns new custom writter for tkg-cli
```suggestion
// NewWriter returns new custom writer
```

2023-03-03 03:35 UTC, marckhouzam commented on log/logger.go
> +	return fmt.Sprintf("%02d%02d %02d:%02d:%02d.%06d %s:%d] ", int(month), day, hour, minute, second, now.Nanosecond()/nanoSecondsPerMicroSecond, file, line)
There is a closing brace but no opening one in this header.

2023-03-06 03:01 UTC, marckhouzam approved these changes
Thanks for addressing all the comments @anujc25.
Very nice improvements you've made!

2023-03-06 03:01 UTC, marckhouzam commented on log/logger.go
> +	showCaller bool
There is currently no API to set this new variable.
But it is ok, we've spent enough time on this PR.  We can add it in another PR.

2023-03-06 03:01 UTC, marckhouzam commented on log/logger.go
> +		header = fmt.Sprintf("%s%s:%d] ", header, file, line)
```suggestion
		header = fmt.Sprintf("%s[%s:%d] ", header, file, line)
```

2023-03-06 19:39 UTC, anujc25 commented on log/logger.go
> +var _ LoggerImpl = &logger{}
It is used to verify `logger` implements all the `LoggerImpl` interface methods.

In this case, we are doing `NewLogger()` so, that function will throw an error if the `logger` is not implementing any `LoggerImpl` function. However, sometimes, you write an interface implementation that should be consumed externally and not internally, it is a good practice to write this statement to verify the implementation is not missing any method implementation required by the interface.

2023-03-06 19:40 UTC, anujc25 commented on log/logger.go
> +		return "[✔] "
Replaced with `[ok]`.

2023-03-06 19:52 UTC, marckhouzam commented on log/logger.go
> +var _ LoggerImpl = &logger{}
This is a great trick!  I wasn't aware of it.  Thanks!

2023-03-06 19:59 UTC, merged