[Draft] Tanzu Plugin Runtime Documentation (docs-draft to main)
vmware-tanzu/tanzu-plugin-runtime pull request #44
Opened 2023-04-04 21:05 UTC by mpanchajanya

### What this PR does / why we need it

### Which issue(s) this PR fixes

Fixes #

### Describe testing done for PR

### Release note

```release-note

```

### Additional information

#### Special notes for your reviewer

2023-04-04 23:06 UTC, chandrareddyp requested changes
I have reviewed the "Configuration API" page, added few comments

2023-04-04 23:06 UTC, chandrareddyp commented on docs/config.md
> +// Delete existing context from CFG_NG by context name
Its not just delete the context from the CFG_NG, it may delete from CFG file also right, for eg, old plugin has added a server, now if we get context, then it returns the servers info, and if we perform `configapi.DeleteContext(serverName)` it does delete the server from the CFG file, if so, we need to update the function documentation properly, other API user may confuse.

2023-04-04 23:12 UTC, mpanchajanya commented on docs/config.md
> +Config library provides various API methods to store DiscoverySources, CLI, Features and environment settings in config.yaml (CFG) and Contexts in config-ng.yaml(CFG_NG) configuration files respectiv
Updated the doc but we need to have discovery sources here we have APIs names Set/Get/DeleteCLIDiscoverySources

2023-04-04 23:12 UTC, mpanchajanya commented on docs/config.md
> +Config library provides various API methods to store DiscoverySources, CLI, Features and environment settings in config.yaml (CFG) and Contexts in config-ng.yaml(CFG_NG) configuration files respectiv
added

2023-04-04 23:21 UTC, mpanchajanya commented on docs/config.md
> +- CFG_NG: Additional configuration file(~/config/tanzu/config_ng.yaml) introduced to store new configuration related types. CFG has to be retained since that is the file that Legacy Plugins rely on t
Added example

2023-04-04 23:24 UTC, mpanchajanya commented on docs/config.md
> +// Delete existing context from CFG_NG by context name
To Avoid encouraging the usage of Servers. We have removed all references of Servers from the documentation and it is deprecated with the new Tanzu CLI.  we expect the users to use Contexts. 
But I see your point its good to have it documented on these APIs that it will update the servers in CFG

2023-04-04 23:43 UTC, mpanchajanya commented
> I have reviewed the "Configuration API" page, added few comments

@chandrareddyp  Addressed the comments. Could you review when you get some time

2023-04-05 16:24 UTC, chandrareddyp approved these changes
LGTM

2023-04-07 16:50 UTC, merged