Add configuration APIs for Certificate configuration
vmware-tanzu/tanzu-plugin-runtime pull request #62
Opened 2023-04-25 17:56 UTC by prkalle

### What this PR does / why we need it
This PR is to add configuration APIs for custom certificate configuration

The sample configuration is shown below which would be added to the configuration file (config-ng.yaml)

```
certs:
    - hostName: localhost:9876
      skipCertVerify: "true"
      insecure: "true"
      caCertData: <REDACTED>
```
### Which issue(s) this PR fixes

Fixes #

### Describe testing done for PR

Unit tests and CI passed

### Release note

```release-note
Add configuration APIs for Certificate configuration
```

### Additional information

#### Special notes for your reviewer

2023-04-25 19:00 UTC, mpanchajanya commented on config/certs.go
> +	cfg, err := convertNodeToClientConfig(node)
nit; pls add hostName validation steps in Get/Delete/Set methods especially if its value is "". so we don't end up have invalid certs like certs without hostname

2023-04-25 19:04 UTC, mpanchajanya commented on config/certs_test.go
> +	tests := []struct {
pls add few negative test cases where Set/Get/Delete return errors
when invalid cert data is used to set/delete/get

2023-04-25 19:07 UTC, mpanchajanya requested changes
Changes LGTM!. nit! on validating the input args and negative test cases

2023-04-26 19:28 UTC, prkalle commented on config/certs.go
> +	cfg, err := convertNodeToClientConfig(node)
Good point. Updated. Thanks

2023-04-26 19:28 UTC, prkalle commented on config/certs_test.go
> +	tests := []struct {
Updated.

2023-04-26 20:42 UTC, mpanchajanya approved these changes

2023-04-26 21:48 UTC, merged