Expose `TANZU_CLI_LOG_LEVEL` environment variable to control the log level
vmware-tanzu/tanzu-plugin-runtime pull request #83
Opened 2023-07-28 18:41 UTC by anujc25

### What this PR does / why we need it

Tanzu Plugin Runtime exposes a logger functionality and also allows logs to be displayed based on the different log levels.
It also exposes API to control the log level for external plugins.

However, we wanted the log levels to be controlled by the user at the runtime so that we can enable more logs for debugging purposes. This PR provides an environment variable `TANZU_CLI_LOG_LEVEL` to control the log level.

The default value of the Tanzu CLI log level is `3`. So any user wanting to see more debug logs should configure `TANZU_CLI_LOG_LEVEL` with value `>3`. 

### Which issue(s) this PR fixes

Fixes #

### Describe testing done for PR

* Manually tested the change.

### Release note

```release-note
Expose the `TANZU_CLI_LOG_LEVEL` environment variable to control the log level
```

### Additional information

#### Special notes for your reviewer

2023-07-28 19:17 UTC, mpanchajanya approved these changes
lgtm! Could you add few unit tests for these with env set, unset ?

2023-07-28 19:31 UTC, chandrareddyp requested changes
looks good!
Could you please add an example like after setting the env TANZU_CLI_LOG_LEVEL variable, how the UX looks for any command.

2023-07-28 19:31 UTC, chandrareddyp commented on log/logger.go
> +		if err == nil {
What if user set incorrect value, and we are not capturing the err here, ignoring the error?
IMO, at minimal we need to warn the error message so that user knows that incorrect value has been set.

2023-07-28 20:36 UTC, marckhouzam reviewed
Typos and a question

2023-07-28 20:36 UTC, marckhouzam commented on log/logger.go
> +	logThresold := defaultLogThreshold
logThresold -> logThreshold

2023-07-28 20:36 UTC, marckhouzam commented on log/logger.go
> +	requestedLogThresoldStr := os.Getenv(EnvTanzuCLILogLevel)
requestedLogThresoldStr -> requestedLogThresholdStr

2023-07-28 20:36 UTC, marckhouzam commented on log/logger.go
> +		requestedLogThresold, err := strconv.ParseUint(requestedLogThresoldStr, 10, 32)
requestedLogThresold -> requestedLogThreshold

2023-07-28 20:36 UTC, marckhouzam commented on log/logger.go
> +	EnvTanzuCLILogLevel = "TANZU_CLI_LOG_LEVEL"
Plugins can use this logging library right?
Should we make the environment variable more generic?

2023-07-28 20:42 UTC, anujc25 commented on log/logger.go
> +	EnvTanzuCLILogLevel = "TANZU_CLI_LOG_LEVEL"
Yes. Considering it is applicable to plugins as well I am using the `TANZU_CLI_LOG_LEVEL` variable. Do you have any other better suggestions?

2023-07-28 20:48 UTC, chandrareddyp approved these changes
LGTM!

2023-07-29 01:23 UTC, marckhouzam commented on log/logger.go
> +	EnvTanzuCLILogLevel = "TANZU_CLI_LOG_LEVEL"
After thinking about a better name, I could not find one. I think what you chose is the best.

2023-07-29 01:27 UTC, marckhouzam approved these changes
LGTM
thanks

2023-07-30 23:14 UTC, merged

2023-07-31 14:24 UTC, marckhouzam reviewed
Sorry for having missed this in my previous review.

2023-07-31 14:24 UTC, marckhouzam commented on log/logger_test.go
> +			logLevel:              "",
This should be a "3" I think

2023-07-31 14:24 UTC, marckhouzam commented on log/logger_test.go
> +			test:                  "when TANZU_CLI_LOG_LEVEL is set to 9",
None of the tests verify the actual boundary, meaning setting the level to X and getting logs at X.
I suggest adding such a test or changing the test for level 9 to use level 8.  Or to add a log at level 9.